### PR TITLE
Database optimisations

### PR DESCRIPTION
**Pull request by lpotherat**
Note : Check admin/modules/sla_categories/models/categories.php with winmerge or another visual file comparator, git didn't diff correctly.

Corrected a bug : text values could not contain quotes.
- added escape functions
- using escape functions in admin

Database optimisation :
- Added indexes on fields concerned by front office access.

### CODE REVIEW

**Comment by wakdev** [comment]
"Note : Check admin/modules/sla_categories/models/categories.php with winmerge or another visual file comparator, git didn't diff correctly."

Yes, I see i must resolve conflicts before merge this commit.
But, good improvement ! Like :)

**Comment by lpotherat** [comment]
Do not forget to use "escape" in future queries ;)

**Comment by lowki** [comment]
Pretty good work up there.
Would be great to use prepared queries too.

**Comment by lpotherat** [comment]
I think it will be my next improvement.

**Comment by wakdev** [comment]
And MySQLi connector :)

**Comment by wakdev** [comment]
I will merge tonight or tomorrow.

**Comment by wakdev** [comment]
I have done merging and resolving conflicts in this commit : https://github.com/wakdev/slash-cms/commit/1ecd1a19d788ff0ea544d7559bf8410052f671dc

So i close this pull request.
Thank you for your great work.

Do not forget to update your fork, because... so many conflicts >_<

**Pull request closed without merging**
